" Basics
syntax on 
set nocompatible
filetype plugin on " for file specific config
filetype plugin indent on
set encoding=utf-8
scriptencoding utf-8

" Quality of life
set path+=**
set novisualbell
set number relativenumber
set textwidth=80
set wildmenu
set wildmode=longest:full,full
set hlsearch
set ruler
set nostartofline
set ignorecase
set smartcase

" Usability options
set clipboard= 
set noerrorbells
set nowrap
set nobackup
set nowritebackup
set viminfo='20,<1000,s1000 
set splitbelow splitright
set mouse=a
set undodir=~/.vim/undodir
set confirm

" Indentation, general indentation. Please check file specific indentation in
" ~/vim/ftplugin
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set smartindent
set autoindent

" Auto parenthesis, brackets, braces 
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

" Custom Commands Clear Vim Registry
command! WipeReg for i in range(34,122) | silent! call setreg(nr2char(i), []) | endfor

" Tag jumping with ctags
command! MakeTags !ctags -R .

" Digraphs Overwrite Subscripts
" for: (ₙ),(ᵢ),(ⱼ),(ₖ)
execute "digraphs ns " . 0x2099         
execute "digraphs is " . 0x1D62         
execute "digraphs js " . 0x2C7C         
execute "digraphs ks " . 0x2096         
" Digraphs Overwrite Superscripts
" for: (ⁿ),(ⁱ),(ʲ),(ᵏ)
execute "digraphs nS " . 0x207f         
execute "digraphs iS " . 0x2071         
execute "digraphs jS " . 0x02b2         
execute "digraphs kS " . 0x1d4f         

" Vim Plug Minimalist Vim plugin Manager
" Instructions  
" https://github.com/junegunn/vim-plug
" Usage add in new plug <url> then save vimrc, then do :PlugInstall 
" Specify a directory for plugins like plugged, don't use name plugin
" To delete the plugin, comment out the Plug below, then run :PlugClean
" To update the plugin, run :PlugUpdate
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/ConradIrwin/vim-bracketed-paste'
Plug 'https://github.com/sheerun/vim-polyglot'
Plug 'https://github.com/tek256/simple-dark'
Plug 'https://github.com/wellle/context.vim'
Plug 'https://github.com/rhysd/vim-clang-format'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'rust-lang/rust.vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
call plug#end()

" For Simple-dark, focus mode
colorscheme simple-dark-transparent
set background=dark

" Underlines spelling, and search has to be after colorscheme to work.
hi keyword cterm=bold
hi SpellBad cterm=underline ctermfg=darkred
hi Search ctermbg=black ctermfg=yellow
au FileType markdown hi Title cterm=bold ctermfg=lightgrey
autocmd BufWritePre *.py :%s/\s\+$//e "remove trailing whitespace in .py

" Snippets
nnoremap ,html :-1read ~/.vim/snippets/skeleton_html.txt<CR>
nnoremap ,python :-1read ~/.vim/snippets/skeleton_py.txt<CR>
nnoremap ,java :-1read ~/.vim/snippets/skeleton_java.txt<CR>
nnoremap ,rust :-1read ~/.vim/snippets/skeleton_rs.txt<CR>
nnoremap ,pylint :-1read ~/.vim/snippets/skeleton_pylint.txt<CR>
nnoremap ,make :-1read ~/.vim/snippets/skeleton_make.txt<CR>
nnoremap ,contact :-1read ~/.vim/snippets/skeleton_contact.txt<CR>

" Golang syntax highlighting
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_structs = 1
let g:go_highlight_methods = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_diagnostic_errors = 1

" Rust stuff
let g:rustfmt_autosave = 1
