"Basics
set nocompatible
syntax on
filetype plugin on
scriptencoding utf-8
set autoindent
set clipboard=
set confirm
set encoding=utf-8
set expandtab "Tabs become spaces
set hlsearch
set ignorecase
set incsearch
set linebreak "Wraps lines at word boundary
set nobackup
set noerrorbells
set nostartofline
set novisualbell
set nowrap
set nowritebackup
set number relativenumber
set path+=**
set ruler
set showmode
set smartcase
set smartindent
set textwidth=80
set ttyfast
set wildmenu

" Set spacing and format in all files by default:
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab

"Vim Plug Minimalist Vim plugin Manager
"Instructions
"https://github.com/junegunn/vim-plug
"Usage add in new plug <url> then save vimrc, then do :PlugInstall
"Specify a directory for plugins like plugged, don't use name plugin
"To delete the plugin, comment out the Plug below, then run :PlugClean
"To update the plugin, run :PlugUpdate
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/ConradIrwin/vim-bracketed-paste'
Plug 'https://github.com/wellle/context.vim'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/tpope/vim-sensible'
Plug 'https://github.com/tpope/vim-tbone'
Plug 'https://github.com/tek256/simple-dark'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

"For Simple-Dark theme plugin
colorscheme simple-dark-transparent
set background=dark

"Netrw configuration
let g:netrw_liststyle=3 "tree view

"Create the tags file
command! MakeTags !ctags -R .

"Remove trailing whitespaces from files
autocmd BufWritePre * :%s/\s\+$//e

"Cursor Change when in Insert Mode and Normal Mode
let &t_SI = "\<esc>[5 q" " blinking I-beam in insert mode
let &t_SR = "\<esc>[3 q" " blinking underline in replace mode
let &t_EI = "\<esc>[ q"  " default cursor (usually blinking block) otherwise

"Auto parenthesis, brackets, braces, and quotes
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap '<CR> ''<ESC><left>
inoremap "<CR> ""<ESC><left>
inoremap <<CR> <><ESC><left>

"Snippets
nnoremap ,html :-1read ~/.vim/snippets/skeleton_html.txt<CR>
nnoremap ,python :-1read ~/.vim/snippets/skeleton_py.txt<CR>
nnoremap ,java :-1read ~/.vim/snippets/skeleton_java.txt<CR>
nnoremap ,rust :-1read ~/.vim/snippets/skeleton_rs.txt<CR>
nnoremap ,pylint :-1read ~/.vim/snippets/skeleton_pylint.txt<CR>
nnoremap ,make :-1read ~/.vim/snippets/skeleton_make.txt<CR>
nnoremap ,contact :-1read ~/.vim/snippets/skeleton_contact.txt<CR>
nnoremap ,poetry :-1read ~/.vim/snippets/skeleton_poetry.txt<CR>

"Toggles Visibility of Line Numbers
nnoremap ,li :call ToggleLineNumbers()<CR>
function! ToggleLineNumbers()
    if &number || &relativenumber
        setlocal nonumber norelativenumber
    else
        setlocal number relativenumber
    endif
endfunction

"Other Hotkeys
"" Ctrl-p to open fzf:
nnoremap <C-p> :Files<Cr>

"" Remap vim yank to system clipboard
nnoremap y "+y
vnoremap y "+y
nnoremap yy "+yy
