#Appearance
PS1="\[\033[01;32m\]eoea: \[\033[0m\]"

# Functionality
set -o vi

# Clears bash_history
cat /dev/null > ~/.bash_history && history -c

# My custom program path
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.local/scripts:${PATH}"

# Repo Path Variables
export REPO="${HOME}/Programming/Repos/github.com/eoea"
export DOTS="${HOME}/Programming/Repos/github.com/eoea/dotfiles"
export NOTES="${HOME}/Programming/Repos/gitlab.com/eoea/coding-notes"
export LAB="${HOME}/Programming/Repos/gitlab.com/eoea/"

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/opt/homebrew/bin:${PATH}"

# Bash-completion Homebrew
[[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"
export PATH="/opt/homebrew/etc/bash_completion.d:${PATH}"

# Golang path environment
# export PATH="${HOME}/.local/bin/go/bin:${PATH}"
export GOPATH="${HOME}/.local/go"
#export GOBIN="${HOME}/.local/go/bin"
# export PATH="${GOPATH}/bin:${PATH}"

# Protobuf path environment
export PATH="${HOME}/.local/bin/protobuf/bin:${PATH}"
export PATH="${HOME}/.local/go/bin/protoc-gen-go:${PATH}"

# Haskell path environment
export PATH="${HOME}/.local/haskell/ghcup:${PATH}"
export PATH="${HOME}/.local/haskell/cabal/bin:${PATH}"
export PATH="${HOME}/.local/haskell/ghcup/bin:${PATH}"

# JVM path environment
export PATH="/opt/homebrew/opt/openjdk.bin:${PATH}"

# Scala path environment
export PATH="${HOME}/Library/Application Support/Coursier/bin:${PATH}"

# LLVM path environment
export PATH="/opt/homebrew/opt/llvm/bin:${PATH}"

# Rust path environment
export RUSTUP_HOME="${HOME}/.rustup"
export CARGO_HOME="${HOME}/.cargo"
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.cargo/env:${PATH}"

# FLAGS
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

# Aliases
alias update="brew update && brew upgrade"
alias ls="ls -G"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias grep="grep --color=auto"
alias ctags="/opt/homebrew/bin/ctags"
