# Appearance
PS1="\[\033[01;32m\]eoea: \[\033[0m\]"

# Functionality
set -o vi

# Clears history on signout
cat /dev/null > ~/.bash_history && history -c

# PATH Variables
export REPO="${HOME}/Programming/Repos/github.com/eoea"
export DOTS="${HOME}/Programming/Repos/github.com/eoea/dotfiles"
export NOTES="${HOME}/Programming/Repos/gitlab.com/eoea/coding-notes"
export GITLAB="${HOME}/Programming/Repos/gitlab.com/eoea/"

# Golang path environment
export PATH="${HOME}/.local/bin/go/bin:${PATH}"
export GOPATH="${HOME}/.local/go"
export GOBIN="${HOME}/.local/go/bin"
export PATH="${GOPATH}/bin:${PATH}"

# Haskell path environment
export PATH="${HOME}/.local/haskell/ghcup:${PATH}"
export PATH="${HOME}/.local/haskell/cabal/bin:${PATH}"
export PATH="${HOME}/.local/haskell/ghcup/bin:${PATH}"

# My Custom Program Path
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.local/scripts:${PATH}"

# Protobuf path environment
export PATH="${HOME}/.local/bin/protobuf/bin:${PATH}"
export PATH="${HOME}/.local/go/bin/protoc-gen-go:${PATH}"

# Aliases
alias update="sudo apt update && apt upgrade"
alias ls="ls --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias grep="grep --color=auto"
